repos:
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0 # Use the latest appropriate tag
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # You can add specific type scopes here if needed 